const MessageTypes = {
  LOGIN: "LOGIN",
  LOGIN_OK: "LOGIN_OK",
  LOGIN_ERROR: "LOGIN_ERROR",
  TEXT_MESSAGE: "TEXT_MESSAGE",
  FILE_START: "FILE_START",
  FILE_CHUNK: "FILE_CHUNK",
  FILE_END: "FILE_END",
  CALL_REQUEST: "CALL_REQUEST",
  CALL_ACCEPT: "CALL_ACCEPT",
  CALL_REJECT: "CALL_REJECT",
  CALL_END: "CALL_END",
  ERROR: "ERROR",
};

module.exports = MessageTypes;
