module.exports = Object.freeze({
  AUTH_REGISTER: "auth:register",
  AUTH_LOGIN: "auth:login",
  AUTH_LOGOUT: "auth:logout",
  APP_BOOTSTRAP: "app:bootstrap",
  CHAT_OPEN: "chat:open",
  CHAT_MESSAGES: "chat:get-messages",
  CHAT_SEND: "chat:send",
  CHAT_DELETE: "chat:delete-message",
  CHAT_PIN: "chat:pin-message",
  CHAT_CLEAR: "chat:clear",
  CHAT_REMOVE: "chat:remove",
  GROUP_CREATE: "group:create",
  GROUP_UPDATE: "group:update",
  FILE_UPLOAD_START: "file:upload-start",
  FILE_UPLOAD_CHUNK: "file:upload-chunk",
  FILE_UPLOAD_END: "file:upload-end",
  FILE_LIST: "file:list",
  FILE_DOWNLOAD: "file:download",
  CALL_START: "call:start",
  CALL_ACCEPT: "call:accept",
  CALL_REJECT: "call:reject",
  CALL_END: "call:end",
  SETTINGS_UPDATE: "settings:update",
  PROFILE_UPDATE: "user:update-profile",
  PROFILE_AVATAR: "user:update-avatar",
  PASSWORD_CHANGE: "user:change-password",
});
